### ISSUE TITLE
Add oyajigyagu 歯医者は廃止や！w

### ISSUE THREAD

**Issue by KisaragiEffective** [gnknzm/crss.gnknzm.net#125]
{"author":"yanorei32","text":"歯医者は廃止や！w","vector_string":"CRSS:1.0/SI:H/GC:H/UK:L/TL:N/CA:L"}

**Comment by yanorei32** [comment]
CA:Hはちがくない？

**Comment by KisaragiEffective** [comment]
> CA:Hはちがくない？

@Ry0taK plz judge this

**Comment by Ry0taK** [comment]
@KisaragiEffective あんまり人に言いたくなるタイプではないのでCA:Lにしておいた
