### ISSUE TITLE
Add oyajigyagu /var を分けるvarいもあるね

### ISSUE THREAD

**Issue by KisaragiEffective** [gnknzm/crss.gnknzm.net#146]
{"author":"yanorei32","text":"/var を分けるvarいもあるね","vector_string":"CRSS:1.0/SI:H/GC:H/UK:M/TL:R/CA:L"}

**Comment by yanorei32** [comment]
わかりやすさのため、「場合」を「varい」にできませんか？

**Comment by KisaragiEffective** [comment]
done
