### ISSUE TITLE
Add oyajigyagu ミントを見んと

### ISSUE THREAD

**Issue by yu-32** [gnknzm/crss.gnknzm.net#390]
{"author":"yu-32","text":"ミントを見んと","vector_string":"CRSS:1.0/SI:H/GC:H/UK:L/TL:N/CA:L"}

**Comment by yanorei32** [comment]
未入力（2）

**Comment by yu-32** [comment]
{"author":"yu-32","text":"ミントを見んと","vector_string":"CRSS:1.0/SI:H/GC:H/UK:L/TL:N/CA:L"}

**Comment by yanorei32** [comment]
あー、下のやつを編集して書いといてください。
