### ISSUE TITLE
Add oyajigyagu 戦車の洗車

### ISSUE THREAD

**Issue by yu-32** [gnknzm/crss.gnknzm.net#391]
{"author":"yu-32","text":"戦車の洗車","vector_string":"CRSS:1.0/SI:H/GC:H/UK:/TL:/CA:"}

**Comment by yanorei32** [comment]
UKとTLとCAが未入力ですがこちらで補完しても?

**Comment by yu-32** [comment]
これどうやらもう言われてたっぽいのでなしで…
