### ISSUE TITLE
Add+oyajigyagu+宰相の殺傷能力、最小

### ISSUE THREAD

**Issue by yu-32** [gnknzm/crss.gnknzm.net#436]
{"author":"yu-32","text":"宰相の殺傷能力、最小","vector_string":"CRSS:1.0/SI:H/GC:H/UK:M/TL:N/CA:L"}

**Comment by yanorei32** [comment]
ユーザーの予備知識、Midじゃないですか？
あと、安直さはHighです。

**Comment by yu-32** [comment]
これ宰相わからない方いますかね…?いるかぁ…
