### ISSUE TITLE
Add oyajigyagu コンセンサスが得られるまで混線さす

### ISSUE THREAD

**Issue by Ry0taK** [gnknzm/crss.gnknzm.net#488]
{"author":"Lenqth","text":"コンセンサスが得られるまで混線さす","vector_string":"CRSS:1.0/SI:H/GC:H/UK:M/TL:N/CA:L"}

**Comment by kory33** [comment]
https://ja.wikipedia.org/wiki/%E3%83%93%E3%82%B6%E3%83%B3%E3%83%81%E3%83%B3%E5%B0%86%E8%BB%8D%E5%95%8F%E9%A1%8C
