### ISSUE TITLE
Add oyajigyagu コンパクトなインパクト

### ISSUE THREAD

**Issue by Siro256** [gnknzm/crss.gnknzm.net#51]
{"author":"RyotaK","text":"コンパクトなインパクト","vector_string":"CRSS:1.0/SI:M/GC:H/UK:L/TL:N/CA:L"}

**Comment by yanorei32** [comment]
いやなんでだよ

**Comment by yanorei32** [comment]
しろ、招待承諾して〜〜〜

**Comment by yanorei32** [comment]
@Siro256 こちらよろしくお願いします。

**Comment by Siro256** [comment]
@yanorei32 様

いつもお世話になっております。

先ほど通知に気づき、対応致しました。
お手数をお掛けしてしまい大変申し訳ございません。

何卒、宜しくお願い致します。

@Siro256

**Comment by yanorei32** [comment]
あれぇ…？
