### ISSUE TITLE
Add oyajigyagu 帆布干すの?

### ISSUE THREAD

**Issue by yu-32** [gnknzm/crss.gnknzm.net#514]
{"author":"yu-32","text":"帆布干すの?","vector_string":"CRSS:1.0/SI:H/GC:M/UK:M/TL:N/CA:L"}

**Comment by yanorei32** [comment]
？

**Comment by Ry0taK** [comment]
https://www.weblio.jp/content/%E5%B8%86%E5%B8%83
「ほぬのほすの」っぽい
