### ISSUE TITLE
2025年問題が存在する

### ISSUE THREAD

**Issue by Ry0taK** [gnknzm/crss.gnknzm.net#632]
`CRE-年-番号`という形式になっているが、`番号`部分が年をまたいでもリセットされず、連番となってしまう問題がある
年を越す前になんとかする... まあ、**連番**になっても**バーレん**か...ｗ

**Comment by yanorei32** [comment]
なんで真面目にIssue書いてるんですか？

**Comment by yanorei32** [comment]
まって！！いまのなし！！！

**Comment by Ry0taK** [comment]
大変申し訳ございません、申し訳程度のギャグを挿入したのでご査収ください
