### ISSUE TITLE
Add oyajigyagu マスターがますますスターになっていく

### ISSUE THREAD

**Issue by kory33** [gnknzm/crss.gnknzm.net#645]
{"author":"RyotaK","text":"マスターがますますスターになっていく","vector_string":"CRSS:1.0/SI:H/GC:H/UK:L/TL:N/CA:L"}

**Comment by yanorei32** [comment]
CAはLっぽいので、Lでマージ。

**Comment by kory33** [comment]
そうなんだ  長さ起因？
