### ISSUE TITLE
Add oyajigyagu このビスはサービスだ

### ISSUE THREAD

**Issue by kory33** [gnknzm/crss.gnknzm.net#647]
{"author":"RyotaK","text":"このビスはサービスだ","vector_string":"CRSS:1.0/SI:H/GC:H/UK:L/TL:N/CA:L"}

**Comment by kory33** [comment]
[question]: ビス、予備知識低でいい？

**Comment by yanorei32** [comment]
CAはLっぽいので、Lでマージ。
