### ISSUE TITLE
Add oyajigyagu 魔法のスマホ

### ISSUE THREAD

**Issue by igameta** [gnknzm/crss.gnknzm.net#681]
{"author":"yanorei32","text":"魔法のスマホ","vector_string":"CRSS:1.0/SI:H/GC:H/UK:L/TL:N/CA:L"}

**Comment by yanorei32** [comment]
これ私ってマジ？

**Comment by yanorei32** [comment]
記憶にございません。

**Comment by igameta** [comment]
相当眠そうだったし仕方ないかも？
