### ISSUE TITLE
Add oyajigyagu データが出たー！

### ISSUE THREAD

**Issue by yu-32** [gnknzm/crss.gnknzm.net#867]
{"author":"yu-32","text":"データが出たー！","vector_string":"CRSS:1.0/SI:H/GC:H/UK:L/TL:N/CA:L"}

**Comment by yanorei32** [comment]
今更だけど、 dup だったわ！ ｶﾞﾊﾊ

https://crss.gnknzm.net/details/?id=CRE-2024-36689
