### ISSUE TITLE
Add oyajigyagu カスのインターネット，カスタネット

### ISSUE THREAD

**Issue by m-tsuru** [gnknzm/crss.gnknzm.net#89]
{"author":"Anonymous","text":"カスのインターネット，カスタネット","vector_string":"CRSS:1.0/SI:L/GC:H/UK:L/TL:N/CA:L"}

**Comment by yanorei32** [comment]
@Ry0taKに確認したところ、Authorの明記が必要なようです。
Issueメッセージを手動にて更新していただけると助かります。 :pray:

**Comment by yanorei32** [comment]
犯人探しが始まっていて、ウケ
https://x.com/sasakulari/status/1804784144981078520

**Comment by m-tsuru** [comment]
人間が見つかるまで、一旦クローズします
